on:
  schedule:
    - cron: "0 0 * * *"
steps:
- uses: actions/checkout@v3
- uses: r-lib/actions/setup-r@v2
  with:
    r-version: '4.2.0' # The R version to download (if necessary) and use. 
    # Use "renv" to retrieve R version recorded in renv.lock file.

- uses: actions/checkout@v3
- uses: r-lib/actions/setup-r@v2
- uses: r-lib/actions/setup-r-dependencies@v2
  with:
    cache-version: 2
    extra-packages: |
      any::ggplot2
      any::rcmdcheck
    needs: |
      website
      coverage

- name: Test
        run: |
          source("R/run_everything.r")
        shell: Rscript {0} 

- name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push         
