name: Update-data
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@master # Set up R runtime
        with:
          r-version: 'release'

      - name: Setup renv # Set up R env to install packages
        run: |
          install.packages('remotes')
          remotes::install_github("rstudio/renv")
        shell: Rscript {0}

      - uses: actions/cache@v2 # Cache packages so won't be compiled everytime job is run
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install dependencies # Install the dependencies eg. Dplyr, tidyverse etc
        run: renv::restore()
        shell: Rscript {0}

      - name: Generate data
              run: source("R/run_everything.r")
              shell: Rscript {0}

      - name: Commit files
              run: |
                git config --local user.email "actions@github.com"
                git config --local user.name "GitHub Actions"
                git add --all
                git commit -am "add data"
                git push
